### ISSUE TITLE
what does `.envrc.disabled` file do?

### ISSUE THREAD

**Issue by caro401** [DHARPA-Project/kiara_plugin.develop#1]
Just trying to understand how the plugin template works and what all the included files are for, and I can't find any information about this kind of file anywhere on the internet

**Comment by makkus** [comment]
You can ignore that, it's just a config file for direnv ( https://direnv.net/ ), useful for me, but we probably shouldn't include that for end-users.

**Comment by caro401** [comment]
thanks for clarifying!
